export default {
  data() {
    return {
      rootURL:
        'https://github.com/venkivijay/Java-Solutions-TCS-Xplore-Proctored-Assessment/tree/master/',
      qa: [
        {
          slug: 'Perfect_Square',
          solutionCount: 1,
          examDate: '2019.12.17',
          tag: [],
          id: 1,
          questionNature: 'Simple',
          examMode: 'PA',
        },
        {
          slug: 'Associate_For_Given_Technology',
          solutionCount: 1,
          examDate: '2019.12.17',
          tag: [],
          id: 2,
          questionNature: 'Complex',
          examMode: 'PA',
        },
        {
          slug: 'Space_Character_Count',
          solutionCount: 1,
          examDate: '2019.12.28',
          tag: [],
          id: 3,
          questionNature: 'Simple',
          examMode: 'PA',
        },
        {
          slug: 'Movie_Get_Movie_By_Genre',
          solutionCount: 1,
          examDate: '2019.12.28',
          tag: [],
          id: 4,
          questionNature: 'Complex',
          examMode: 'PA',
        },
        {
          slug: 'Character_At_Odd_Position',
          solutionCount: 1,
          examDate: '2020.01.15',
          tag: [],
          id: 5,
          questionNature: 'Simple',
          examMode: 'PA',
        },
        {
          slug: 'Sim_Match_And_Sort',
          solutionCount: 1,
          examDate: '2020.01.15',
          tag: [],
          id: 6,
          questionNature: 'Complex',
          examMode: 'PA',
        },
        {
          slug: 'Last_Character_In_Every_Word',
          solutionCount: 1,
          examDate: '2020.01.25',
          tag: [],
          id: 7,
          questionNature: 'Simple',
          examMode: 'PA',
        },
        {
          slug: 'Inventory_Replenish',
          solutionCount: 1,
          examDate: '2020.01.25',
          tag: [],
          id: 8,
          questionNature: 'Complex',
          examMode: 'PA',
        },
        {
          slug: 'Vowels_Consonants_Count',
          solutionCount: 1,
          examDate: '2020.02.10',
          tag: [],
          id: 9,
          questionNature: 'Simple',
          examMode: 'PA',
        },
        {
          slug: 'Player_Get_Average_of_Runs',
          solutionCount: 1,
          examDate: '2020.02.10',
          tag: [],
          id: 10,
          questionNature: 'Complex',
          examMode: 'PA',
        },
        {
          slug: 'Smallest_Vowel_in_a_String',
          solutionCount: 1,
          examDate: '2020.02.13',
          tag: [],
          id: 11,
          questionNature: 'Simple',
          examMode: 'PA',
        },
        {
          slug: 'Reverse_Number',
          solutionCount: 2,
          examDate: '2020.03.02',
          tag: [],
          id: 12,
          questionNature: 'Simple',
          examMode: 'PA',
        },
        {
          slug: 'Medicine_Get_Price_by_Disease',
          solutionCount: 1,
          examDate: '2020.03.02',
          tag: [],
          id: 13,
          questionNature: 'Complex',
          examMode: 'PA',
        },
        {
          slug: 'Reverse_String',
          solutionCount: 2,
          examDate: '2020.04.02',
          tag: [],
          id: 14,
          questionNature: 'Simple',
          examMode: 'Hackathon',
        },
        {
          slug: 'Unique_Characters',
          solutionCount: 1,
          examDate: '2020.04.02',
          tag: [],
          id: 15,
          questionNature: 'Simple',
          examMode: 'Hackathon',
        },
        {
          slug: 'Device_Management',
          solutionCount: 1,
          examDate: '2020.04.02',
          tag: [],
          id: 16,
          questionNature: 'Complex',
          examMode: 'Hackathon',
        },
        {
          slug: 'Data_Transmission',
          solutionCount: 1,
          examDate: '2020.04.02',
          tag: [],
          id: 17,
          questionNature: 'Complex',
          examMode: 'Hackathon',
        },
        {
          slug: 'Institution',
          solutionCount: 1,
          examDate: '2020.04.17',
          tag: [],
          id: 18,
          questionNature: 'Complex',
          examMode: 'Hackathon',
        },
        {
          slug: 'Player_Get_Player_Based_On_Level',
          solutionCount: 1,
          examDate: '2020.05.08',
          tag: [],
          id: 19,
          questionNature: 'Complex',
          examMode: 'OPA',
        },
        {
          slug: 'Movie_Find_Avg_Budget_By_Director',
          solutionCount: 1,
          examDate: '2020.06.05',
          tag: [],
          id: 20,
          questionNature: 'Complex',
          examMode: 'OPA',
        },
        {
          slug: 'AutonomousCar',
          solutionCount: 1,
          examDate: '2020.06.19',
          tag: [],
          id: 21,
          questionNature: 'Complex',
          examMode: 'OPA',
        },
        {
          slug: 'NavalVessel',
          solutionCount: 1,
          examDate: '2020.07.03',
          tag: [],
          id: 22,
          questionNature: 'Complex',
          examMode: 'OPA',
        },
        {
          slug: 'Travel_Agencies',
          solutionCount: 1,
          examDate: '2020.07.17',
          tag: [],
          id: 23,
          questionNature: 'Complex',
          examMode: 'OPA',
        },
      ],
    };
  },
  computed: {
    getQuestion(id) {
      return `${this.rootURL}${this.qa[id - 1].slug}/Question.md`;
    },
    getSolutions(id) {
      const solutions = [];
      for (let i = 0; i < this.qa[id - 1].solutionCount; i++) {
        solutions.push(
          `${this.rootURL}${this.qa[id - 1].slug}/Solution${i + 1}.md`,
        );
      }
      return solutions;
    },
  },
};
